// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfyjrebaabhajevquvtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1meWpyZWJhYWJoYWpldnF1dnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjAwMTgsImV4cCI6MjA3MzEzNjAxOH0.-7prTOk3kgLCgO23fEmaePxZeueLpozNH2dcOze0Tus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});